pdf("dos_elipses - Bayes con Histogramas")
x <- read.csv("dos_elipses.predic", header=FALSE , sep='\t')
plot(x[,1],x[,2],col=x[,3]+2,main='Gráfica de dos_elipses.predic - Bayes con Histogramas',xlab='input2',ylab='input2')
dev.off()
x <- read.csv("ejC.predic", header=FALSE , sep='\t')
pdf("ejC - Bayes con Histogramas")
plot(x[,1],x[,2],col=x[,3]+2,main='Gráfica de ejC.predic - Bayes con Histogramas',xlab='input1',ylab='input2')
dev.off()
